const STORAGE_KEY='itda-jeonbuk-demo';
const profiles=[
 {id:1,name:'서연',age:24,gender:'여성',area:'전주',job:'디자이너',intro:'카페에서 이야기 나누는 걸 좋아하고 주말에는 전시를 보러 다녀요. 편안하게 오래 이야기할 수 있는 관계를 좋아해요.',tags:['카페','전시','산책'],style:'차분한 대화',emoji:'☕'},
 {id:2,name:'민지',age:26,gender:'여성',area:'익산',job:'간호사',intro:'맛있는 걸 찾아다니는 걸 좋아하고 여행 계획 세우는 것도 좋아해요. 서로의 일상을 존중하는 연애를 하고 싶어요.',tags:['맛집','여행','드라이브'],style:'알콩달콩',emoji:'🌷'},
 {id:3,name:'하은',age:25,gender:'여성',area:'군산',job:'마케터',intro:'새로운 공간에 가는 걸 좋아해요. 영화와 음악 이야기를 같이 나눌 수 있는 사람이면 좋겠어요.',tags:['영화','음악','카페'],style:'취미 공유',emoji:'🎬'},
 {id:4,name:'지우',age:27,gender:'여성',area:'전주',job:'공무원',intro:'조용한 산책이나 맛집 탐방을 좋아합니다. 주말에 가까운 곳으로 소소하게 떠나는 걸 좋아해요.',tags:['산책','맛집','여행'],style:'편안한 만남',emoji:'🌿'},
 {id:5,name:'채원',age:23,gender:'여성',area:'완주',job:'대학생',intro:'게임도 좋아하고 귀여운 소품 구경도 좋아해요. 친구처럼 편하게 시작하는 관계를 선호해요.',tags:['게임','소품샵','카페'],style:'친구처럼',emoji:'🎮'},
 {id:6,name:'수빈',age:28,gender:'여성',area:'정읍',job:'회계직',intro:'책 읽는 걸 좋아하고 대화가 잘 통하는 사람에게 끌려요. 약속과 신뢰를 중요하게 생각해요.',tags:['독서','산책','카페'],style:'차분한 대화',emoji:'📚'}
];
const state={mode:'login',page:'home',step:0,profile:{},selectedTags:[]};
const steps=[
 {key:'area',title:'어디에서 생활하고 있나요?',desc:'정확한 주소 대신 시·군 단위만 입력해요.',options:['전주','익산','군산','정읍','남원','김제','완주','무주','부안','고창','임실','순창','진안','장수']},
 {key:'job',title:'현재 어떤 일을 하고 있나요?',desc:'현재 생활 패턴과 관심사를 이해하는 데 활용해요.',options:['대학생','직장인','공무원','자영업','프리랜서','취업준비생','전문직','기타']},
 {key:'age',title:'나이를 알려주세요.',desc:'성인 사용자만 참여할 수 있어요.',range:true},
 {key:'gender',title:'성별을 선택해주세요.',desc:'매칭 과정에서 상대 성별 선호와 함께 사용돼요.',options:['여성','남성','선택하지 않음']},
 {key:'looking',title:'어떤 만남을 찾고 있나요?',desc:'본인이 원하는 관계의 방향을 선택해주세요.',options:['가벼운 데이트부터','진지한 연애','장기적인 만남','친구처럼 천천히']},
 {key:'interest',title:'관심사를 골라주세요.',desc:'최대 5개까지 선택할 수 있어요.',multi:true,options:['카페','맛집','여행','산책','영화','음악','전시','독서','게임','운동','사진','요리','반려동물','드라이브','공연']},
 {key:'style',title:'데이트 스타일은 어떤 편인가요?',desc:'첫 만남의 분위기를 정할 때 활용해요.',options:['차분한 대화','알콩달콩','취미 공유','액티비티','맛집 탐방','조용한 산책']},
 {key:'intro',title:'당신을 한 문장으로 소개해주세요.',desc:'여기 적어준 문장은 AI가 성향을 이해하는 데 활용해요.',text:true}
];
function getData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return{}}}
function saveData(data){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function currentUser(){return getData().user||null}
function render(){const app=document.querySelector('#app'); if(state.page==='home') return renderHome(app); if(state.page==='onboarding') return renderOnboarding(app); if(state.page==='matching') return renderMatching(app); if(state.page==='browse') return renderBrowse(app);}
function topbar(){const user=currentUser();return `<header class="topbar"><div class="brand"><div class="brand-mark">잇</div><span>잇다 전북</span></div><div class="nav-actions">${user?`<span class="helper">${esc(user.nickname)}님</span><button class="ghost-btn" onclick="logout()">로그아웃</button>`:''}</div></header>`}
function renderHome(app){app.innerHTML=`<div class="shell">${topbar()}<main class="hero"><div class="hero-inner"><span class="eyebrow">● 전북 청년 연결 프로젝트</span><h1>전북에서 만나고,<br/><em>관계를 이어가다.</em></h1><p>잇다 전북은 생활지역, 직업, 관심사와 자기소개를 바탕으로 서로 잘 맞는 사람을 찾도록 돕는 지역 기반 만남 서비스입니다.</p><div class="choice-grid"><button class="choice-card" onclick="protectedRoute('onboarding')"><div class="choice-icon">✎</div><h2>내 정보 입력</h2><p>사는 지역부터 관심사와 데이트 스타일, 자기소개까지 한 단계씩 작성해요.</p><span class="arrow">시작하기 →</span></button><button class="choice-card" onclick="protectedRoute('matching')"><div class="choice-icon">✦</div><h2>AI 매칭</h2><p>내 프로필과 상대 후보를 비교해 AI가 잘 맞는 이유까지 설명해줘요.</p><span class="arrow">매칭 보기 →</span></button><button class="choice-card" onclick="protectedRoute('browse')"><div class="choice-icon">♡</div><h2>사람 둘러보기</h2><p>전북 곳곳의 다양한 프로필을 카드 형태로 살펴볼 수 있어요.</p><span class="arrow">둘러보기 →</span></button></div><div class="info-strip"><div><strong>AI가 보는 것은 조건만이 아니에요.</strong><span>지역 생활권 · 관심사 · 대화 스타일 · 관계 방향을 함께 고려합니다.</span></div><button class="outline-btn" onclick="showNotice('프로토타입에서는 가상의 프로필로 매칭을 시연합니다.')">서비스 안내</button></div></div></main></div>`}
function protectedRoute(page){if(!currentUser())return openAuth('login',page); state.page=page; render();}
function openAuth(mode='login',after='home'){state.mode=mode;state.after=after;const wrap=document.createElement('div');wrap.className='modal-wrap';wrap.id='auth-modal';wrap.innerHTML=authHtml();document.body.appendChild(wrap)}
function authHtml(){const signup=state.mode==='signup';return `<div class="modal"><h2>${signup?'회원가입':'로그인'}</h2><p class="sub">잇다 전북은 로그인 후 서비스를 이용할 수 있어요.</p><div class="tabs"><button class="tab ${!signup?'active':''}" onclick="switchAuth('login')">로그인</button><button class="tab ${signup?'active':''}" onclick="switchAuth('signup')">회원가입</button></div><div class="field"><label>이메일</label><input id="auth-email" type="email" placeholder="example@email.com" /></div><div class="field"><label>비밀번호</label><input id="auth-password" type="password" placeholder="6자 이상" /></div>${signup?`<div class="field"><label>닉네임</label><input id="auth-nickname" placeholder="화면에 표시될 이름" /></div>`:''}<button class="primary-btn" onclick="submitAuth()">${signup?'회원가입하고 시작하기':'로그인하고 시작하기'}</button><p class="helper">※ 현재 프로토타입은 브라우저 저장소를 이용한 데모 인증입니다. 실제 서비스에서는 서버 인증/DB로 교체합니다.</p></div>`}
function switchAuth(mode){state.mode=mode;const modal=document.querySelector('#auth-modal');if(modal)modal.innerHTML=authHtml()}
function submitAuth(){const email=document.querySelector('#auth-email')?.value.trim();const pw=document.querySelector('#auth-password')?.value;const nick=document.querySelector('#auth-nickname')?.value.trim();if(!email||!pw||(state.mode==='signup'&&!nick))return showNotice('필수 정보를 모두 입력해주세요.');if(state.mode==='signup'&&pw.length<6)return showNotice('비밀번호는 6자 이상으로 입력해주세요.');let data=getData();if(state.mode==='signup'){data.user={email,nickname:nick};data.profile=data.profile||{};saveData(data);showNotice('회원가입이 완료됐어요.');}else{if(!data.user||data.user.email!==email)return showNotice('가입된 계정을 찾지 못했어요. 먼저 회원가입을 해주세요.');showNotice('로그인됐어요.');}document.querySelector('#auth-modal')?.remove();state.page=state.after||'home';render()}
function logout(){localStorage.removeItem(STORAGE_KEY);state.page='home';state.profile={};render();showNotice('로그아웃했어요.')}
function renderOnboarding(app){const step=steps[state.step];const profile=getData().profile||{};app.innerHTML=`<div class="shell">${topbar()}<main class="app-page"><div class="page-head"><div><h1>내 정보 입력</h1><p>한 단계씩 답하면 나에게 맞는 만남을 찾는 데 활용돼요.</p></div><button class="outline-btn" onclick="state.page='home';render()">처음으로</button></div><div class="stepper">${steps.map((_,i)=>`<div class="step-dot ${i<=state.step?'active':''}"></div>`).join('')}</div><section class="form-card"><div class="question"><div class="small">STEP ${state.step+1} / ${steps.length}</div><h2>${step.title}</h2><p>${step.desc}</p>${step.range?`<div class="range-wrap"><input id="age" type="range" min="19" max="50" value="${profile.age||25}" oninput="document.querySelector('#age-val').textContent=this.value+'세'"/><div id="age-val" class="range-val">${profile.age||25}세</div></div>`:step.text?`<textarea id="intro" rows="7" placeholder="예: 익산에서 일하고 있고 주말에는 카페나 전시를 찾아다녀요. 편하게 대화하고 천천히 친해지는 관계를 좋아합니다.">${esc(profile.intro||'')}</textarea>`:`<div class="choices">${step.options.map(o=>`<button class="choice-chip ${(step.multi?(state.selectedTags||profile.interest||[]).includes(o):profile[step.key]===o)?'selected':''}" onclick="pickOption('${step.key}','${o}',${!!step.multi})">${o}</button>`).join('')}</div>`}<div class="form-footer">${state.step>0?'<button class="secondary-btn" onclick="prevStep()">← 이전</button>':'<span></span>'}<button class="next-btn" onclick="nextStep()">${state.step===steps.length-1?'프로필 저장':'다음 →'}</button></div></div></section></main></div>`}
function pickOption(key,value,multi){const data=getData();data.profile=data.profile||{};if(multi){const arr=Array.isArray(data.profile[key])?data.profile[key]:[];if(arr.includes(value))data.profile[key]=arr.filter(x=>x!==value);else if(arr.length<5)data.profile[key]=[...arr,value];else return showNotice('관심사는 최대 5개까지 선택할 수 있어요.');state.selectedTags=data.profile[key];}else data.profile[key]=value;saveData(data);renderOnboarding(app=document.querySelector('#app'))}
function nextStep(){const data=getData();data.profile=data.profile||{};const s=steps[state.step];if(s.range){data.profile.age=Number(document.querySelector('#age').value)}if(s.text){const v=document.querySelector('#intro').value.trim();if(!v)return showNotice('자기소개를 한 줄이라도 작성해주세요.');data.profile.intro=v}if(!data.profile[s.key]&& !s.range && !s.multi)return showNotice('하나를 선택해주세요.');if(s.multi&&(data.profile[s.key]||[]).length===0)return showNotice('관심사를 하나 이상 선택해주세요.');saveData(data);if(state.step<steps.length-1){state.step++;render()}else{showNotice('프로필이 저장됐어요. 이제 AI 매칭을 시작할 수 있어요.');state.page='matching';state.step=0;render()}}
function prevStep(){if(state.step>0){state.step--;render()}}
function renderMatching(app){const user=currentUser();const p=getData().profile||{};const candidates=profiles.filter(x=>x.gender!==p.gender);const ranked=candidates.map(x=>({...x,score:score(p,x)})).sort((a,b)=>b.score-a.score);app.innerHTML=`<div class="shell">${topbar()}<main class="app-page"><div class="page-head"><div><h1>AI 매칭 결과</h1><p>${user?esc(user.nickname):'회원'}님의 프로필을 바탕으로 잘 맞는 순서대로 보여드려요.</p></div><button class="outline-btn" onclick="state.page='onboarding';render()">프로필 수정</button></div><div class="filter-row"><span class="badge">✦ AI 분석 완료</span><span class="filter">생활권 반영</span><span class="filter">관심사 반영</span><span class="filter">데이트 스타일 반영</span></div><div class="match-grid">${ranked.slice(0,4).map(matchCard).join('')}</div></main></div>`}
function score(p,x){let score=55;if(p.area&&x.area===p.area)score+=18;else if((p.area==='전주'||p.area==='완주')&&(x.area==='전주'||x.area==='완주'))score+=10;if(p.job&&['직장인','공무원','전문직','자영업'].includes(p.job)&&['직장인','공무원','전문직','자영업'].includes(x.job))score+=4;const interests=Array.isArray(p.interest)?p.interest:[];score+=interests.filter(t=>x.tags.includes(t)).length*5;if(p.style&&p.style===x.style)score+=9;if(p.looking==='진지한 연애'&&x.age>=24)score+=3;return Math.min(99,score)}
function explain(p,x){const reasons=[];if(p.area===x.area)reasons.push(`${x.area} 생활권이 같아 실제로 만나기 편해요.`);else if((p.area==='전주'||p.area==='완주')&&(x.area==='전주'||x.area==='완주'))reasons.push('전주·완주 생활권이 가까워 만남 빈도를 만들기 좋아요.');const common=(p.interest||[]).filter(t=>x.tags.includes(t));if(common.length)reasons.push(`${common.join(', ')} 취향이 겹쳐 대화 소재가 많아요.`);if(p.style===x.style)reasons.push(`둘 다 '${x.style}' 스타일의 데이트를 선호해요.`);if(!reasons.length)reasons.push('프로필의 생활패턴과 관계 방향을 종합해 매칭했어요.');return reasons.slice(0,2).join(' ')}
function matchCard(x){const p=getData().profile||{};return `<article class="match-card"><div class="match-top"><div style="display:flex;gap:13px;align-items:center"><div class="avatar">${x.emoji}</div><div><div class="match-name">${x.name} · ${x.age}</div><div class="meta">${x.area} · ${x.job}</div></div></div><span class="badge">${x.score}%</span></div><div class="tags">${x.tags.map(t=>`<span class="tag">${t}</span>`).join('')}<span class="tag">${x.style}</span></div><div class="reason">✦ <strong>AI 매칭 이유</strong><br/>${explain(p,x)}</div><p class="meta" style="line-height:1.6;margin:13px 0 0">${x.intro}</p><div class="card-actions"><button class="like" onclick="showNotice('${x.name}님에게 관심을 보냈어요.')">관심 보내기</button><button class="more" onclick="showProfile(${x.id})">프로필 보기</button></div></article>`}
function renderBrowse(app){app.innerHTML=`<div class="shell">${topbar()}<main class="app-page"><div class="page-head"><div><h1>사람 둘러보기</h1><p>전북 곳곳의 다양한 프로필을 한눈에 살펴보세요.</p></div><button class="outline-btn" onclick="state.page='matching';render()">AI 매칭으로</button></div><div class="filter-row"><button class="filter" onclick="shuffleProfiles()">지역: 전북 전체</button><button class="filter" onclick="showNotice('원하는 지역 필터를 추가할 수 있어요.')">직업 필터</button><button class="filter" onclick="showNotice('관심사 필터를 추가할 수 있어요.')">관심사 필터</button></div><div class="match-grid" id="browse-grid">${profiles.map(x=>matchCard({...x,score:Math.floor(72+Math.random()*22)})).join('')}</div></main></div>`}
function shuffleProfiles(){profiles.sort(()=>Math.random()-.5);renderBrowse(document.querySelector('#app'));showNotice('프로필을 새로 섞어봤어요.')}
function showProfile(id){const x=profiles.find(p=>p.id===id);if(!x)return;const wrap=document.createElement('div');wrap.className='modal-wrap';wrap.id='profile-modal';wrap.innerHTML=`<div class="modal"><div style="display:flex;gap:14px;align-items:center"><div class="avatar">${x.emoji}</div><div><h2 style="margin:0">${x.name} · ${x.age}</h2><div class="meta">${x.area} · ${x.job}</div></div></div><div class="tags" style="margin-top:20px">${x.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><p style="line-height:1.8;color:#5d6577">${x.intro}</p><div class="reason">데이트 스타일 · ${x.style}</div><div class="card-actions" style="margin-top:20px"><button class="like" onclick="document.querySelector('#profile-modal').remove();showNotice('${x.name}님에게 관심을 보냈어요.')">관심 보내기</button><button class="more" onclick="document.querySelector('#profile-modal').remove()">닫기</button></div></div>`;document.body.appendChild(wrap)}
function showNotice(msg){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
window.protectedRoute=protectedRoute;window.openAuth=openAuth;window.switchAuth=switchAuth;window.submitAuth=submitAuth;window.logout=logout;window.pickOption=pickOption;window.nextStep=nextStep;window.prevStep=prevStep;window.showNotice=showNotice;window.showProfile=showProfile;window.shuffleProfiles=shuffleProfiles;window.state=state;
render();